---

- name: render /etc/foreman-installer/scenarios.d/foreman-answers.yaml
  template:
    src: foreman-answers.yaml.j2
    dest: /etc/foreman-installer/scenarios.d/foreman-answers.yaml
    owner: root
    group: root
    mode: '0600'
  notify: foreman-installer
  tags:
    - foreman-answers

- name: call foreman-installer right away
  meta: flush_handlers

- name: insert ssl_* directives (see https://github.com/theforeman/puppet-foreman/issues/441)
  blockinfile:
    dest: /etc/foreman/settings.yaml
    insertbefore: '# Log settings'
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    content: |
      :ssl_ca_file: {{ foreman_ssl_ca_certificate_file }}
      :ssl_certificate: {{ foreman_ssl_certificate_file }}
      :ssl_priv_key: {{ foreman_ssl_certificate_key_file }}
  tags:
    - foreman-settings
