---

- name: install puppetlabs repo
  package:
    name: "http://yum.puppetlabs.com/puppetlabs-release-el-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: install epel-release
  package:
    name: "epel-release"
    state: present

- name: install foreman repo
  package:
    name: "http://yum.theforeman.org/releases/{{ foreman_version }}/el{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/foreman-release.rpm"
    state: present

- name: install foreman-installer
  package:
    name: "foreman-installer"
    state: present
